### ISSUE TITLE
Chromium-browser Probelm

### ISSUE THREAD

**Issue by braindef** [matthieugras/Prime-Ubuntu-18.04#11]
If i install your tool that really seems to work for battery consumption (thank you for that) but my chromium-browser does not work anymore if i switch to intel with prime-select intel.

I tried also the Deb from Googles website but there it has the same problem.

If i switch back to nvidia with prime-select nvidia chromium works again.

unfortunately i cannot find out what it could be and thought that you maybe already found out what it could be.

With kind regards
Marc Landolt

Acer Predator Helios 300 / NH.Q3EEZ.001 / PH317-52-7919
(Intel Coffeelake && NVIDIA GTX 1050 Ti)

what i found out about this device so far:
https://marclandolt.ch/ml_buzzernet/2018/07/04/installation-ubuntu-auf-acer-predator-helios-300-nh-q3eez-001-ph317-52-7919/

**Comment by braindef** [comment]
I found out, that the problem comes maybe from the light db, if i switch back to gdm3 with dpkg-reconfigure gdm3 and select gdm and restart my system chromium is working again.

then two things that could maybe make sense:
1. if you look at cat /etc/X11/default-display-manager you can find what display manager is runing and restart not just the lightdm but also the gdm if it is running
2. maybe you should thell the user that you hardcore kill the xserver and the display manager, because if he has unsaved work he or she would maybe loose things...

With kind regards
Marc Landolt

PS: Keep on doing stuff :) :+1:

**Comment by matthieugras** [comment]
Yes, at the time I was doing this I was using Xubuntu, so lightdm was the default dm. Currently I'm using this on Fedora KDE but it required some additional tweaks. I'm planning to make it work more reliably across different distributions and display managers in the future. 
But in the long run I would prefer to rely on more complete and centralized solutions. There are some interesting approaches:
- https://github.com/solus-project/linux-driver-management
- Newer versions of Ubuntu's GPU-manager
