### ISSUE TITLE
endless loop of PKCS#7 when running "sudo prime-select nvidia"

### ISSUE THREAD

**Issue by 3togo** [matthieugras/Prime-Ubuntu-18.04#8]
Jun 27 16:31:00 eli-UX310 kernel: [  861.501162] PKCS#7 signature not signed with a trusted key
Jun 27 16:31:20 eli-UX310 kernel: [  881.990418] PKCS#7 signature not signed with a trusted key
Jun 27 16:31:31 eli-UX310 kernel: [  892.198321] PKCS#7 signature not signed with a trusted key
Jun 27 16:31:31 eli-UX310 kernel: [  892.429230] PKCS#7 signature not signed with a trusted key
Jun 27 16:31:31 eli-UX310 kernel: [  892.609742] PKCS#7 signature not signed with a trusted key

**Comment by matthieugras** [comment]
Disable secure boot in your BIOS/EFI. The kernel won't load unsigned modules (nvidia) when it's booted with secure boot enabled.

**Comment by 3togo** [comment]
Solved.

make sure you are at nvidia mode before running "sudo make install"

in simple term


```
`eli@eli-UX310:~$ sudo /usr/bin/prime-select nvidia
[sudo] password for eli: 
Info: the nvidia profile is already set
eli@eli-UX310:~$ cd git/others/Prime-Ubuntu-18.04/
.git/         prime_socket/ 
eli@eli-UX310:~$ cd git/others/Prime-Ubuntu-18.04/prime_socket/
src/    target/ 
eli@eli-UX310:~$ cd git/others/Prime-Ubuntu-18.04/prime_socket/src/
eli@eli-UX310:src$ sudo make install
#sudo cp 10-monitor.conf /usr/share/X11/xorg.conf.d/
cd .. && sudo cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
sudo cp nvidia-prime-boot.service /etc/systemd/system/
sudo cp prime-socket.service /etc/systemd/system/
sudo cp prime-select /usr/local/bin
sudo cp turnoff_nvidia_at_boot /usr/local/bin
sudo rm -f /usr/local/bin/prime_socket
sudo cp ../target/debug/prime_socket /usr/local/bin
sudo chmod +x /usr/local/bin/prime-select
sudo chmod +x /usr/local/bin/prime_socket
sudo chmod +x /usr/local/bin/turnoff_nvidia_at_boot
sudo systemctl enable prime-socket.service
sudo systemctl start prime-socket.service
```

**Comment by 3togo** [comment]
"PKCS#7 signature not signed with a trusted key"  simply means that I am using a proprietary driver.
https://unix.stackexchange.com/questions/118116/what-is-a-tainted-kernel-in-linux

**Comment by matthieugras** [comment]
ok

**Comment by 3togo** [comment]
matthieugras,

thank your for your scripts. 

Joe

**Comment by 3togo** [comment]
matthieugras,

thank your for your scripts.  

Joe

**Comment by 3togo** [comment]
Below is the patch to "check nvidia mode" before doing "make install"
[check_nvidia_mode_before_make_install.patch.txt](https://github.com/matthieugras/Prime-Ubuntu-18.04/files/2143186/check_nvidia_mode_before_make_install.patch.txt)
